CM.make "sources.cm";
print "====================Test1=====================\n";
Main.compileverb "../tests/test1.tig" 3;
print "====================Test2=====================\n";
Main.compileverb "../tests/test2.tig" 3;
print "====================Test3=====================\n";
Main.compileverb "../tests/test3.tig" 3;
print "====================Test4=====================\n";
Main.compileverb "../tests/test4.tig" 3;
print "====================Test5=====================\n";
Main.compileverb "../tests/test5.tig" 3;
print "====================Test6=====================\n";
Main.compileverb "../tests/test6.tig" 3;
print "====================Test7=====================\n";
Main.compileverb "../tests/test7.tig" 3;
print "====================Test8=====================\n";
Main.compileverb "../tests/test8.tig" 3;
print "====================Test12=====================\n";
Main.compileverb "../tests/test12.tig" 3;
print "====================Test27=====================\n";
Main.compileverb "../tests/test27.tig" 3;
print "====================Test30=====================\n";
Main.compileverb "../tests/test30.tig" 3;
print "====================Test37=====================\n";
Main.compileverb "../tests/test37.tig" 3;
print "====================Test41=====================\n";
Main.compileverb "../tests/test41.tig" 3;
print "====================Test42=====================\n";
Main.compileverb "../tests/test42.tig" 3;
print "====================Test44=====================\n";
Main.compileverb "../tests/test44.tig" 3;
print "====================Test46=====================\n";
Main.compileverb "../tests/test46.tig" 3;
print "====================Test47=====================\n";
Main.compileverb "../tests/test47.tig" 3;
print "====================Test48=====================\n";
Main.compileverb "../tests/test48.tig" 3;
print "====================Merge======================\n";
Main.compileverb "../tests/merge.tig" 3;
print "====================Queens=====================\n";
Main.compileverb "../tests/queens.tig" 3;

